### ISSUE TITLE
Keep components using consistent

### ISSUE THREAD

**Issue by yberkut** [KaraliA/toBeReviewed#4]
`<Header />`
vs
`<to-do-list />`

**Comment by KaraliA** [comment]
Is it normal to use Header component as <header />? 
Or it's better to give another alias to it? 
When I used, Vue.js was angry and didn't render component at all.

**Comment by KaraliA** [comment]
Everything is good. Thank you so much for your time and ‘giving’🤗

**Comment by iberkut** [comment]
;)

**Comment by iberkut** [comment]
@KaraliA it's not possible to give your component the same name as pre-defined tag names as "header". It's common practice to give unique names like 'myapp-header' or 'MyappHeader'.
